# Generated by Django 3.1.1 on 2020-09-25 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('hr', models.FloatField()),
                ('o2sat', models.FloatField()),
                ('temp', models.FloatField()),
                ('sbp', models.FloatField()),
                ('map', models.FloatField()),
                ('dbp', models.FloatField()),
                ('resp', models.FloatField()),
                ('etco2', models.FloatField()),
                ('baseexcess', models.FloatField()),
                ('hco3', models.FloatField()),
                ('fio2', models.FloatField()),
                ('ph', models.FloatField()),
                ('paco2', models.FloatField()),
                ('sao2', models.FloatField()),
                ('ast', models.FloatField()),
                ('bun', models.FloatField()),
                ('alkalinephos', models.FloatField()),
                ('calcium', models.FloatField()),
                ('chloride', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('bilirubin_direct', models.FloatField()),
                ('glucose', models.FloatField()),
                ('lactate', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('phosphate', models.FloatField()),
                ('potassium', models.FloatField()),
                ('bilirubin_total', models.FloatField()),
                ('troponini', models.FloatField()),
                ('hct', models.FloatField()),
                ('hgb', models.FloatField()),
                ('ptt', models.FloatField()),
                ('wbc', models.FloatField()),
                ('fibrinogen', models.FloatField()),
                ('platelets', models.FloatField()),
                ('age', models.FloatField()),
                ('gender', models.FloatField()),
                ('hospadmtime', models.FloatField()),
                ('iculos', models.FloatField()),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
