# Generated by Django 3.1.1 on 2020-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEndPoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='sepsislabel',
            field=models.FloatField(default=0.0),
        ),
    ]
