# Generated by Django 3.1.1 on 2020-09-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIEndPoint', '0002_patients_sepsislabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='name',
        ),
    ]
