# Generated by Django 3.1.1 on 2020-09-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIEndPoint', '0002_auto_20200923_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='datetime',
        ),
    ]
