# Generated by Django 3.1.1 on 2020-09-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEndPoint', '0003_remove_patients_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='datetime',
            field=models.DateTimeField(default='2020-09-16T18:10:30.779Z'),
        ),
    ]
