# Generated by Django 3.1.1 on 2020-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIEndPoint', '0004_patients_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
